version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      kotlin-ecosystem:
        type: maven-repository
        url: https://maven.pkg.github.com/Kotlin/declarative-gradle-jetbrains-ecosystem-plugin
        username: dependabot
        password: ${{ secrets.GITHUB_TOKEN }}
