name: Dependency review for pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/dependency-submission@v3
        with:
          cache-encryption-key: ${{ secrets.CC }}

      - uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'
