name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-slim

    permissions:
      packages: read

    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
